---

- name: run kibana container
  docker_container:
    name: elastiflow-kibana
    image: docker.elastic.co/kibana/kibana-oss:7.5.2
    restart_policy: always
    network_mode: host
    env:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "5601"
      ELASTICSEARCH_HOSTS: "http://127.0.0.1:9200"
      KIBANA_DEFAULTAPPID: "dashboard/653cf1e0-2fd2-11e7-99ed-49759aed30f5"
      LOGGING_QUIET: "true"