---

- name: install softflowd
  apt:
    name: softflowd
    state: latest
    update_cache: yes

- name: configure softflowd
  copy:
    src: default.conf
    dest: /etc/softflowd/default.conf
  notify:
    - reload softflowd

- name: pause play until url is reachable from this host
  uri:
    url: "http://localhost:5601/app/kibana"
    follow_redirects: none
    method: GET
  register: _result
  until: _result.status == 200
  retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5 # Every 5 seconds

- name: download dashboards
  shell: 'curl -o /tmp/elastiflow.kibana.7.5.x.ndjson https://raw.githubusercontent.com/robcowart/elastiflow/master/kibana/elastiflow.kibana.7.5.x.ndjson'
  register: result

- name: upload the dashboards to kibana
  shell: 'curl -X POST "http://localhost:5601/api/saved_objects/_import" -H "kbn-xsrf: true" --form file=@/tmp/elastiflow.kibana.7.5.x.ndjson'
  register: result

- name: get the public ip address of the server
  shell: curl http://ifconfig.me
  register: result

- debug: 
    msg: "Deploying to cloud? Here is the public IP address http://{{ result.stdout }}:5601 to load elastiflow"

